In [2]:
import os
import pandas as pd

In [16]:
strong = pd.read_csv('data/health/strong.csv', delimiter=';', escapechar='\\')

In [4]:
strong

,Date,Workout Name,Exercise Name,Set Order,Weight,Weight Unit,Reps,RPE,Distance,Distance Unit,Seconds,Notes,Workout Notes
0,2020-08-31 12:00:00,Treino A,Bench Press (Barbell),1.0,50,kg,8.0,NaN,NaN,NaN,0.0,NaN,NaN
1,2020-08-31 12:00:00,Treino A,Bench Press (Barbell),2.0,50,kg,8.0,NaN,NaN,NaN,0.0,NaN,NaN
2,2020-08-31 12:00:00,Treino A,Bench Press (Barbell),3.0,50,kg,8.0,NaN,NaN,NaN,0.0,NaN,NaN
3,2020-08-31 12:00:00,Treino A,Incline Bench Press (Dumbbell),1.0,12,kg,8.0,NaN,NaN,NaN,0.0,Fiz +1 set porque pensei que ia aquecer com 12...,NaN
4,2020-08-31 12:00:00,Treino A,Incline Bench Press (Dumbbell),2.0,12,kg,8.0,NaN,NaN,NaN,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7058,2021-03-19 18:11:45,Treino D,Seated Calf Raise (Plate Loaded),4.0,80,kg,15.0,NaN,NaN,NaN,0.0,NaN,NaN
7059,2021-03-19 18:11:45,Treino D,Standing Calf Raise (Machine),1.0,100,kg,30.0,NaN,NaN,NaN,0.0,NaN,NaN
7060,2021-03-19 18:11:45,Treino D,Standing Calf Raise (Machine),2.0,100,kg,30.0,NaN,NaN,NaN,0.0,NaN,NaN
7061,2021-03-19 18:11:45,Treino D,Standing Calf Raise (Machine),3.0,100,kg,25.0,NaN,NaN,NaN,0.0,NaN,NaN
7062,2021-03-19 18:11:45,Treino D,Standing Calf Raise (Machine),4.0,100,kg,20.0,NaN,NaN,NaN,0.0,NaN,NaN

In [34]:
strong.loc[(strong.Date == 'Dedos. "')]

Empty DataFrame
Columns: [Date, Workout Name, Exercise Name, Set Order, Weight, Weight Unit, Reps, RPE, Distance, Distance Unit, Seconds, Notes, Workout Notes]
Index: []

In [46]:
strong.loc[~strong.Date.str.startswith('20')]

,Date,Workout Name,Exercise Name,Set Order,Weight,Weight Unit,Reps,RPE,Distance,Distance Unit,Seconds,Notes,Workout Notes
2291,"90s rest entre as pernas. 30s na Ãºltima. """,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4009,ExecuÃ§Ã£o mt melhor. Mais confianÃ§a. SÃ³ preciso...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN